version: '3'

services:
    php-fpm:
        build:
            context: docker/php-fpm
        volumes:
            - ../:/var/www
    nginx:
        build:
            context: docker/nginx
        volumes:
            - ../:/var/www
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/sites/:/etc/nginx/sites-available
            - ./nginx/conf.d/:/etc/nginx/conf.d
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - php-fpm
            - database
    database:
        build:
            context: docker/database
        ports:
          - "3306:3306"
        environment:
            - MYSQL_DATABASE=boosttypers
            - MYSQL_USER=boost
            - MYSQL_PASSWORD=typers
            - MYSQL_ROOT_PASSWORD=typers2